### ISSUE TITLE
Convert config file to YAML

### ISSUE THREAD

**Issue by e0da** [justinforce/lirc_scripts#1]
Example:

``` yaml
- command: my_script --with-options and/arguments
  keys:
    - RECORD_KEY
    - STOP_KEY
- command: other_script
  keys:
    - POWER_KEY
```
